export const CREATE_RESOURCE = 'CREATE_RESOURCE';
export const UPDATE_RESOURCE = 'UPDATE_RESOURCE';
export const DELETE_RESOURCE = 'DELETE_RESOURCE';

export const FETCH_RESOURCES_REQUEST = 'FETCH_RESOURCES_REQUEST';
export const FETCH_RESOURCES_SUCCESS = 'FETCH_RESOURCES_SUCCESS';
export const FETCH_RESOURCES_FAILURE = 'FETCH_RESOURCES_FAILURE';

export const SAVE_RESOURCE = 'SAVE_RESOURCE';

export const SEARCH_RESOURCES_REQUEST = 'SEARCH_RESOURCES_REQUEST';
export const SEARCH_RESOURCES_SUCCESS = 'SEARCH_RESOURCES_SUCCESS';
export const SEARCH_RESOURCES_FAILURE = 'SEARCH_RESOURCES_FAILURE';

export const FETCH_RESOURCES = 'FETCH_RESOURCES';
export const SEARCH_RESOURCES = 'SEARCH_RESOURCES';