export const FETCH_RESOURCES_REQUEST = 'FETCH_RESOURCES_REQUEST';
export const FETCH_RESOURCES_SUCCESS = 'FETCH_RESOURCES_SUCCESS';
export const FETCH_RESOURCES_FAILURE = 'FETCH_RESOURCES_FAILURE';

export const SAVE_RESOURCE_REQUEST = 'SAVE_RESOURCE_REQUEST';
export const SAVE_RESOURCE_SUCCESS = 'SAVE_RESOURCE_SUCCESS';
export const SAVE_RESOURCE_FAILURE = 'SAVE_RESOURCE_FAILURE';

export const SET_SEARCHTERM = 'SET_SEARCHTERM';
